apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitlab
  namespace: gitlab
spec:
#ce bloc je suis pas sure que c'est correcte 
  selector:
    matchLabels:
      service: gitlab

  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: gitlab
    spec:
      containers:
      - env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: GITLAB_OMNIBUS_CONFIG
        image: gitlab/gitlab-ce:latest
        name: gitlab
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 4567
        resources: {}
        volumeMounts:
          - mountPath: /var/opt/gitlab
            name:  gitlab-pv-claim-1
          - mountPath: /var/log/gitlab
            name: gitlab-pv-claim-2
          - mountPath: /etc/gitlab
            name: gitlab-pv-claim-3        
      restartPolicy: Always
      volumes:
        - name: gitlab-pv-claim-1
          persistentVolumeClaim:
            claimName: gitlab-pv-claim-1
        - name: gitlab-pv-claim-2
          persistentVolumeClaim:
            claimName: gitlab-pv-claim-2
        - name: gitlab-pv-claim-3
          persistentVolumeClaim:
            claimName: gitlab-pv-claim-3
status: {}